// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyWVwpKl-wAgbgIAPxXfLKzcAzYsidU6Y',
    appId: '1:584618041481:web:108497f4f5232bc203e658',
    messagingSenderId: '584618041481',
    projectId: 'tirolevent-5e282',
    authDomain: 'tirolevent-5e282.firebaseapp.com',
    storageBucket: 'tirolevent-5e282.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfg9Fbo1yr0iunK-MQtCpKT6utLk8r6aM',
    appId: '1:584618041481:android:e3e081753a61f8c403e658',
    messagingSenderId: '584618041481',
    projectId: 'tirolevent-5e282',
    storageBucket: 'tirolevent-5e282.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2_-NInq3SeolzoTOjLnQziJJxJoRa0hg',
    appId: '1:584618041481:ios:dee6cb1ed100781b03e658',
    messagingSenderId: '584618041481',
    projectId: 'tirolevent-5e282',
    storageBucket: 'tirolevent-5e282.appspot.com',
    iosClientId: '584618041481-358sfoh08cm65tbh7c5iml2pee1qqrgc.apps.googleusercontent.com',
    iosBundleId: 'com.example.tirolevents',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2_-NInq3SeolzoTOjLnQziJJxJoRa0hg',
    appId: '1:584618041481:ios:cf49a7a90cd8486003e658',
    messagingSenderId: '584618041481',
    projectId: 'tirolevent-5e282',
    storageBucket: 'tirolevent-5e282.appspot.com',
    iosClientId: '584618041481-omhm6s8198kvtp7e8d1vv2i3l88vvein.apps.googleusercontent.com',
    iosBundleId: 'com.example.tirolevents.RunnerTests',
  );
}
